spring:
  application:
    name: backend-app
  
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: kt
    password: kt123
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: none        # SQL 스크립트를 먼저 실행하도록 설정
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  
  sql:
    init:
      mode: never           # SQL 스크립트 비활성화, JPA가 처리하도록
  
  jackson:
    time-zone: Asia/Seoul

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: info
    com.kt.backendapp: DEBUG

---
# 개발용 프로파일 설정
spring:
  config:
    activate:
      on-profile: dev
